### ISSUE TITLE
AnnotationBear: Mandatory parameter language breaks old coala

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1012]
The `.coafile` on coala branches releases/0.8 and releases/0.7 (and presumably earlier releases) causes the following error on CircleCI, because of language:

```
coala-ci -L DEBUG

[ERROR][15:26:50] During execution, we found that some required settings were not provided. They are:
language (from AnnotationBear) -  The programming language of the source code.
[ERROR][15:26:50] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][15:26:50] Exception was:
Traceback (most recent call last):

  File "/opt/circleci/python/3.5.1/lib/python3.5/site-packages/coalib/coala_main.py", line 74, in run_coala
    arg_list=arg_list)

  File "/opt/circleci/python/3.5.1/lib/python3.5/site-packages/coalib/settings/ConfigurationGathering.py", line 355, in gather_configuration
    log_printer)

  File "/opt/circleci/python/3.5.1/lib/python3.5/site-packages/coalib/settings/SectionFilling.py", line 43, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/opt/circleci/python/3.5.1/lib/python3.5/site-packages/coalib/settings/SectionFilling.py", line 89, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/opt/circleci/python/3.5.1/lib/python3.5/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError

coala-ci -L DEBUG returned exit code 255
```

Probably related is that an earlier command is doing `pip install coala-bears colorama==0.3.6 --pre -U`, which drags in `coala_bears-0.9.0.dev20161117113755-py3-none-any.whl`, which in turn drags in `coala-0.9.0.dev20161118131029` , replacing the 0.8 or 0.7 installed from the repo.

**Comment by jayvdb** [comment]
`KeywordBear` added a dependency on  `AnnotationBear` in 1da70cde , and `AnnotationBear` has always had this mandatory non-defaulted parameter `language`. 

PR https://github.com/coala/coala-bears/pull/884 , closing issue https://github.com/coala/coala-bears/issues/761 .
