### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Lidilidian** [coala/coala-bears#1025]
i've got this error when i remove 'use_spaces' from SpaceConsistencyBear in .coafile

```
[ERROR][17:28:46] During execution, we found that some required settings were not provided. They are:
use_spaces (from SpaceConsistencyBear) - True if spaces are to be used instead of tabs.
[ERROR][17:28:46] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][17:28:46] Exception was:
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/coalib/coala_main.py", line 74, in run_coala
    arg_list=arg_list)

  File "/usr/lib/python3.4/site-packages/coalib/settings/ConfigurationGathering.py", line 353, in gather_configuration
    log_printer)

  File "/usr/lib/python3.4/site-packages/coalib/settings/SectionFilling.py", line 43, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/usr/lib/python3.4/site-packages/coalib/settings/SectionFilling.py", line 89, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/usr/lib/python3.4/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError
```

**Comment by jayvdb** [comment]
This occurs when you use `coala-ci`?

**Comment by Lidilidian** [comment]
yes mr @jayvdb

**Comment by jayvdb** [comment]
Could you edit the title and first post of this issue to explain the command you used to see this error

**Comment by jayvdb** [comment]
And then retry with the latest code from master, because `coala-ci` has just recently been deprecated.

**Comment by abhishalya** [comment]
@jayvdb I was able to reproduce the error for this issue. The error occurs due to the removal of the `use_spaces` which should be assigned to a boolean value 'True' (if spaces are used) and 'False' (if tabs are used instead of spaces). The error does mention this in the error log.

**Comment by abhishalya** [comment]
@jayvdb Sorry for late response. This is the complete error:

```
(mycoalabears) abhishalya@bhushan-X556UR:~/local_dev/coala-bears$ coala-ci
WARNING:root:Use of `coala-ci` binary is deprecated, use `coala --non-interactive` instead.
[ERROR][15:30:12] During execution, we found that some required settings were not provided. They are:
use_spaces (from SpaceConsistencyBear) - True if spaces are to be used instead of tabs.
[ERROR][15:30:12] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][15:30:12] Exception was:
Traceback (most recent call last):

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/SectionFilling.py", line 42, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/SectionFilling.py", line 88, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError

```

Also I would like to mention that the `coala --non-interactive` produces the same error:

```
(mycoalabears) abhishalya@bhushan-X556UR:~/local_dev/coala-bears$ coala --non-interactive
[ERROR][15:30:24] During execution, we found that some required settings were not provided. They are:
use_spaces (from SpaceConsistencyBear) - True if spaces are to be used instead of tabs.
[ERROR][15:30:24] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][15:30:24] Exception was:
Traceback (most recent call last):

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/SectionFilling.py", line 42, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/settings/SectionFilling.py", line 88, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/home/abhishalya/local_dev/mycoalabears/lib/python3.6/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError

```

**Comment by abhishalya** [comment]
@jayvdb I think its not what you were expecting of. I guess the exception should be handled if the `use_spaces` is not defined in the `.coafile` for the SpaceConsistencyBear.

**Comment by jayvdb** [comment]
Great, thanks for confirming the problem still exists.  We'll schedule this to be worked on.
