### ISSUE TITLE
Output appropriate message if the language given in input is not valid/not supported for KeywordBear

### ISSUE THREAD

**Issue by aptrishu** [coala/coala-bears#1256]
If I put this in .coafile

`[Default]  
language = anything  
bears = KeywordBear  
files = javaji/test.cs  
use_spaces = yeah  
file_naming_convention = pascal  
keywords = \#warning`  

and run `coala -V` , I get this  

`Traceback (most recent call last):  
  File "/home/rishus23/venv/coala/lib/python3.4/site-packages/coalib/bears/Bear.py", line 240, in   execute  
    return [] if result is None else list(result)  
  File "/home/rishus23/venv/coala/lib/python3.4/site-packages/bears/general/KeywordBear.py", line 104, in run  
    keyword.start())  
  File "/home/rishus23/venv/coala/lib/python3.4/site-packages/bears/general/KeywordBear.py", line 30, in generate_diff  
    c for c in comments if todo_source_range in c]  
  File "/home/rishus23/venv/coala/lib/python3.4/site-packages/bears/general/KeywordBear.py", line 30, in <listcomp>  
    c for c in comments if todo_source_range in c]  
  File "/home/rishus23/venv/coala/lib/python3.4/site-packages/bears/general/KeywordBear.py", line 22, in _get_comments  
    yield from result.contents.get('comments', [])  
AttributeError: 'str' object has no attribute 'get'  
`

**Comment by aptrishu** [comment]
![coala_post](https://cloud.githubusercontent.com/assets/22702242/21655337/a04f9404-d2df-11e6-8627-f22b1c7ec14b.png)

**Comment by aptrishu** [comment]
![coala_post](https://cloud.githubusercontent.com/assets/22702242/21655383/c7c64bd6-d2df-11e6-8100-d12911b1dc88.png)

**Comment by Techievena** [comment]
I want to work on this

**Comment by Techievena** [comment]
cobot assign #1256

**Comment by Techievena** [comment]
Well I got this result
![coala](https://cloud.githubusercontent.com/assets/17270966/21740498/8a412d36-d4e1-11e6-8204-da998b1f9f1b.png)

**Comment by Techievena** [comment]
And also in documentation it is written supported languages as all

**Comment by Techievena** [comment]
I also think the fix I have applied is a hacky solution (Well I have not yet written a test case for it) , but it isn't the actual method I guess?

**Comment by aptrishu** [comment]
Check my comment on you PR.
