### ISSUE TITLE
Can't use nmedtuples in bears

### ISSUE THREAD

**Issue by aptrishu** [coala/coala-bears#1352]
When I try to use namedtuples in bears this creates an error

```Cython
Process Process-63:
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/coalib/processes/BearRunning.py", line 535, in run
    control_queue)
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/coalib/processes/BearRunning.py", line 417, in run_local_bears
    filename)
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/coalib/processes/BearRunning.py", line 300, in run_local_bears_on_file
    local_result_dict[filename] = local_result_list
  File "<string>", line 2, in __setitem__
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/managers.py", line 716, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'bears.general.AnnotationBear.multiline_string'>: attribute lookup multiline_string on bears.general.AnnotationBear failed
```
Actually pickle requires namedtuples to be defined module global, but that is not always the right way to solve it.
Solution - maybe use pickle from dill ( https://github.com/uqfoundation)
or anything else ?

**Comment by Makman2** [comment]
You need to define `__module__` on your named tuple to point to your current module when creating it dynamically. Python can't know where you generate your type^^ (we recently found out for linter bears...)

**Comment by Makman2** [comment]
@aptrishu though how do you use your namedtuple?

**Comment by aptrishu** [comment]
@Makman2 
Please take a look here.. https://github.com/coala/coala-bears/pull/1332/files#diff-cdac3a46c1e8f21576bf1cbd87170148R19
