### ISSUE TITLE
Move away from running setuptools shims to invoke Python linters

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1526]
setuptools created wrapper executable scripts depend on setuptools (actually `pkg_resources`), which exposes coala to whatever issues that may bring since we don't lock down the setuptools version, and it is generally unwise to pin the setuptools version as different versions as there are constantly new bug fixes , unintended regressions and intentional removal of features and support for various Python versions and recently there was a requirement that setuptools was installed with pip and could not be self-installed.

As an example of the problems that causes, my `yamllint` on Fedora is currently
```py
#!/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'yamllint==1.5.0','console_scripts','yamllint'
__requires__ = 'yamllint==1.5.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('yamllint==1.5.0', 'console_scripts', 'yamllint')()
    )
```
Note that it is 1.5.0, whereas coala requires 1.6.0 .

with yamllint 1.6.0 installed with `pip install --user`, I get the unhelpful backtrace

```py
$  yamllint .gitlab-ci.yml 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (yamllint 1.6.1 (/home/jayvdb/.local/lib/python3.6/site-packages), Requirement.parse('yamllint==1.5.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/yamllint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'yamllint==1.5.0' distribution was not found and is required by the application
```

These types of problems can be eliminated with regular use of virtualenvs, but another useful approach is to reduce the reliance on setuptools by executing scripts with `python -m <module>`, which means we can also load the package within the existing runtime, saving a lot of overhead in linter startup (which currently happens per file).

This is somewhat related to #929 , as Python linters of Python need to be able to run on a specific version of the Python runtime.  In that case the user wants to pick whether a Python 2 or 3 runtime is used, and relying on the setuptools created wrapper script introduces an un-managable reliance on the user having correctly installed everything.

Steps:

1. Check each Python linter package has a `__main__`, and create bugs or PRs upstream (e.g. https://github.com/adrienverge/yamllint/pull/45) for any which do not.  This is a low difficultly task.

2. switch our linters to using `sys.executable -m <linter package>` for any linter which should behave the same way irrespective of the python runtime.  This is lots of low difficulty tasks.,

3. Allowing the `sys.executable` component to be modified per linter, so most linters can be run on the main runtime while specific linters can be run on python2 where necessary, as requested by user.  i.e. solve #929

**Comment by jack17529** [comment]
1. Looks like a line of code.
2. Using sys.executable with the module flag for python runtime.
3. The linter which require python 2 using sys.executable .

Please tell weather I understand it right @jayvdb ?
