### ISSUE TITLE
Installing from source fails

### ISSUE THREAD

**Issue by kaustubhhiware** [coala/coala-bears#1579]
While installing from source, the following error log is faced : 

```
Obtaining file:///home/coala-bears
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python3.5/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
        @_call_aside
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 645, in _build_master
        ws = cls()
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 638, in __init__
        self.add_entry(entry)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 694, in add_entry
        for dist in find_distributions(entry, True):
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2030, in find_on_path
        path_item, entry, metadata, precedence=DEVELOP_DIST
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2449, in from_location
        py_version=py_version, platform=platform, **kw
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2789, in _reload_version
        md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2414, in _version_from_file
        line = next(iter(version_lines), '')
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2582, in _get_metadata
        for line in self.get_metadata_lines(name):
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1472, in get_metadata_lines
        return yield_lines(self.get_metadata(name))
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1469, in get_metadata
        return value.decode('utf-8') if six.PY3 else value
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 215: invalid start byte
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/coala-bears/
```

I've reinstalled python3 and all pip3 packages, but the error appears only while installing coala-bears from source.

The local repo is in sync with the latest commit `5b5d7de`

**Comment by kaustubhhiware** [comment]
The latest commit `72bc27f` solved this issue. Closing.
