### ISSUE TITLE
HTMLLintBear does not run on Windows 10

### ISSUE THREAD

**Issue by latacz-io** [coala/coala-bears#1747]
I was trying to run the HTMLLintBear to fix #1741 but it doesnt run:

`PS C:\Users\Sebastian\python> coala -b HTMLLintBear -f issue1741.htm -V
[WARNING][16:45:29] The default coafile '.coafile' was not found. You can generate a configuration file with your curren
t options by adding the `--save` flag or suppress any use of config files with `-I`.
[DEBUG][16:45:29] Platform Windows -- Python 3.5.2, coalib 0.12.0.dev99999999999999
[DEBUG][16:45:29] Since the configuration settings have changed since the last run, the cache will be flushed and rebuil
t.
[DEBUG][16:45:29] The file cache was successfully flushed.
Executing section cli...
[DEBUG][16:45:29] Files that will be checked:
c:\users\sebastian\python\issue1741.htm
[DEBUG][16:45:30] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use
 the `--flush-cache` flag to see them.
[DEBUG][16:45:30] Running bear HTMLLintBear...
[WARNING][16:45:30] Bear HTMLLintBear failed to run on file c:\users\sebastian\python\issue1741.htm. Take a look at debu
g messages (`-V`) for further information.
[DEBUG][16:45:30] The bear HTMLLintBear raised an exception. If you are the author of this bear, please make sure to cat
ch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "c:\users\sebastian\python\coala\coala\coalib\bears\Bear.py", line 281, in execute
    result = self.run_bear_from_section(args, kwargs)
  File "c:\users\sebastian\python\coala\coala\coalib\bears\Bear.py", line 274, in run_bear_from_section
    return self.run(*args, **kwargs)
  File "c:\users\sebastian\python\coala\coala\coalib\bearlib\abstractions\Linter.py", line 657, in run
    self.debug("Running '{}'".format(' '.join(arguments)))
TypeError: sequence item 1: expected str instance, NoneType found`

**Comment by Makman2** [comment]
Do you have `html_lint.py` installed? If it's not found, then this error occurs.

But we should catch that definitely better, as nobody would understand what to do in this case^^

**Comment by fneu** [comment]
What exactly need to be installed, though?
```PS C:\Users\fabian\devel\test> pip install html-linter
Requirement already satisfied: html-linter in c:\users\fabia\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: template-remover in c:\users\fabia\appdata\local\programs\python\python36\lib\site-packag
es (from html-linter)
Requirement already satisfied: docopt>=0.6.1 in c:\users\fabia\appdata\local\programs\python\python36\lib\site-packages
(from html-linter)

PS C:\Users\fabian\devel\test> pip install html-lint
Collecting html-lint
  Could not find a version that satisfies the requirement html-lint (from versions: )
No matching distribution found for html-lint```

**Comment by Makman2** [comment]
hm seems like `html-linter` is it.

**Comment by fneu** [comment]
Well, it's installed and the error still appears. On Linux it's fine, but I 
can reproduce the problem on Windows.


Am 19. Mai 2017 1:27:12 nachm. schrieb Mischa Krüger 
<notifications@github.com>:

**Comment by Makman2** [comment]
Oh that's bad. Have you tracked down the reason?

**Comment by fneu** [comment]
I didn't dig very deep, but I'm pretty sure that `HTMLLintBear` cannot find `html_lint` in spite of that being installed and accessible via the cli (Windows powershell in this case).

The juicy bit is this at the very end of the trace:

```
  File "c:\users\sebastian\python\coala\coala\coalib\bearlib\abstractions\Linter.py", line 657, in run
    self.debug("Running '{}'".format(' '.join(arguments)))
TypeError: sequence item 1: expected str instance, NoneType found
```

On linux, where everything runs fine, the `arguments` are:
```
('/usr/bin/python3', '/usr/bin/html_lint.py', '--disable=', '/home/fabian/devel/test/test.html')
```

On windows, the second argument is `None`.

**Comment by Makman2** [comment]
I'm not sure if `which` works on python scripts, as only `cmd` and `bat` are supported as far as I know. And powershell != cmd sadly :/
I'll take a look too soon :+1:

**Comment by jayvdb** [comment]
Is this a Windows 10 specific problem?

fwiw, it works on Appveyor
https://ci.appveyor.com/project/coala/coala-bears/build/1.0.6430/job/72gdlkobnesx8d1e#L332
(and also on the 64 bit build)

**Comment by fneu** [comment]
I have no idea and cannot test anything besides windows 10, but I'll take a closer look at the appveyor setup, maybe there is another necessary step, like messing with paths or something. 

I can only say that the exact same steps concerning installation via pip and coala execution worked on a fresh linux install and did not work on a fresh windows install. (I just got a new hard drive recebtly)

**Comment by jayvdb** [comment]
I got the same error with an older version of the package : https://travis-ci.org/jayvdb/docker-coala-base/builds/248989641
