### ISSUE TITLE
GitCommitBear: Exception on empty commit message body

### ISSUE THREAD

**Issue by userzimmermann** [coala/coala-bears#2031]
When there is only a shortlog but no further body in the commit message, the following happens:

```python
Traceback (most recent call last):
  File "c:\users\zimmermann\projects\coala\lib\coalib\bears\Bear.py", line 308, in execute
    return [] if result is None else list(result)
  File "c:\users\zimmermann\projects\coala\bears\bears\vcs\git\GitCommitBear.py", line 134, in run
    **self.get_issue_checks_metadata().filter_parameters(kwargs))
  File "c:\users\zimmermann\projects\coala\bears\bears\vcs\git\GitCommitBear.py", line 302, in check_issue_reference
    body = body.splitlines()[-1]
IndexError: list index out of range
```

**Comment by Makman2** [comment]
This is blocking another PR, taking over.
