### ISSUE TITLE
CheckStyleBear is not Working

### ISSUE THREAD

**Issue by aashutoshrathi** [coala/coala-bears#2065]
```sh
Executing section CheckStyleBear...
[ERROR][14:44:51] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][14:44:51] Exception was:
Traceback (most recent call last):

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()

  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)

  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)

  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)

  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)

socket.timeout: The read operation timed out


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ncu.dl.sourceforge.net', port=443): Read timed out. (read timeout=20)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/coala_main.py", line 113, in run_coala
    console_printer=console_printer)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/processes/Processing.py", line 710, in execute_section
    console_printer=console_printer)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/processes/Processing.py", line 384, in instantiate_processes
    console_printer=console_printer)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/processes/Processing.py", line 321, in instantiate_bears
    timeout=0.1)]

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/processes/Processing.py", line 315, in <listcomp>
    local_bear_list = [bear

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/processes/Processing.py", line 291, in filter_raising_callables
    yield elem(*args, **kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coala_utils/decorators.py", line 429, in decorated
    return function(*args, **kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/bears/Bear.py", line 244, in __init__
    self.setup_dependencies()

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/bears/java/CheckstyleBear.py", line 58, in setup_dependencies
    'checkstyle-6.19.jar')

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/coalib/bears/Bear.py", line 463, in download_cached_file
    response = requests.get(url, stream=True, timeout=20)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)

  File "/home/aashutoshrathi/.local/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ncu.dl.sourceforge.net', port=443): Read timed out. (read timeout=20)

```

This timeout occured when I tried to apply patches.

**Comment by SanketDG** [comment]
Are you sure this is not an internet/proxy issue, I see that the connection is getting timed out when its downloading the jar file

**Comment by aashutoshrathi** [comment]
Oh, sorry I fixed it.

**Comment by Makman2** [comment]
Though the message is quite bad... we should fix it.
