### ISSUE TITLE
ESLintBear: Missing plugin just throws a warning and coala won't reanalyze files again

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2158]
Missing plugin errors should probably be turned into exceptions:
```
[WARNING][17:50:35] While running ESLintBear, some issues were found:
[WARNING][17:50:35] Failed to load plugin prettier: Cannot find module 'eslint-plugin-prettier'
Error: Failed to load plugin prettier: Cannot find module 'eslint-plugin-prettier'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.load (/coala-bears/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.loadAll (/coala-bears/node_modules/eslint/lib/config/plugins.js:136:21)
    at Object.load (/coala-bears/node_modules/eslint/lib/config/config-file.js:505:21)
    at loadConfig (/coala-bears/node_modules/eslint/lib/config.js:64:33)
    at new Config (/coala-bears/node_modules/eslint/lib/config.js:199:38)
```
Next run:
```
Executing section all...
Executing section cli...
```
Although the `prettier` plugin was still not installed, coala had now a clean run.

**Comment by sibasish14** [comment]
I would like to work on this issue.
Can someone tell me how to proceed?

**Comment by Makman2** [comment]
Please read the issue title and description ;)

**Comment by sibasish14** [comment]
@Makman2  please assign it to me. I'll give it a try.

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by Prabhat-IIT** [comment]
@Makman2  how can I reproduce the error?

**Comment by Makman2** [comment]
Write an `eslint_config` that requires a plugin you don't have installed, and run the bear.

**Comment by sangamcse** [comment]
Got the issue. Let me try to solve it @Makman2 😃

**Comment by sangamcse** [comment]
@Makman2, what I noticed is that when we run ESLintBear 1st time, it checks like you explained in https://github.com/coala/coala-bears/issues/2158#issue-280828722 and in next run (without using `--flush-cache`), it passes the run.
Here is the debug message: 
> coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.

**Comment by Makman2** [comment]
Yeah and this is the problem. It shall always fail if you haven't the plugin installed and return an error code.
Also if you now install some missing plugins, you would now be able to actually run the analysis, but coala won't now because it thinks it already has analyzed the files (because the bear just returns without results, which signalizes coala that everything went fine). This produces just more work for the developer to reset the cache again to make the analysis working. Things are just inconsistent here, and this should be fixed.
