### ISSUE TITLE
Issues with python3.3 travis check

### ISSUE THREAD

**Issue by virresh** [coala/coala-bears#2488]
We only check for the unsupported python versions now on very specific PRs (direct push to master branch only), so it is hard to see it happening in other cases as well.

The issue as quoted from travis builds:
```
Searching for bandit~=1.2
Reading https://pypi.python.org/simple/bandit/
Best match: bandit 1.4.0
Downloading https://files.pythonhosted.org/packages/45/b2/f5a4adb1e7773e6d631481b784ad49e6ec56aa81e9fdafcabf0fe3e0241a/bandit-1.4.0.tar.gz#sha256=cb977045497f83ec3a02616973ab845c829cdab8144ce2e757fe031104a9abd4
Processing bandit-1.4.0.tar.gz
Writing /tmp/easy_install-euwn9c/bandit-1.4.0/setup.cfg
Running bandit-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-euwn9c/bandit-1.4.0/egg-dist-tmp-ib9fmh
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/__init__.py", line 124, in __init__
    _Command.__init__(self,dist)
  File "/opt/python/3.3.6/lib/python3.3/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-euwn9c/bandit-1.4.0/setup.cfg: TypeError: dist must be a Distribution instance
+retval=1
+set +x
setup.py error code 1 ok
```

needs more investigation, 
Example builds of this issue: 

https://travis-ci.org/virresh/coala-bears/builds/380033068
https://travis-ci.org/coala/coala-bears/builds/378397254

**Comment by jayvdb** [comment]
I think this is the same problem as https://github.com/coala/coala-bears/pull/2268#issuecomment-383362257 , but there are too many other build issues causing problems to see that the fix worked
