### ISSUE TITLE
Appveyor failed during setting up a safety module

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/coala-bears#2511]
Traceback:
```
  Downloading https://files.pythonhosted.org/packages/a7/52/202ef7a64b92a3c4648aa9604cb7c13816eb1af06b5edcb958383b0c910a/safety-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-w123vuon\safety\setup.py", line 7, in <module>
        readme = readme_file.read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 776: character maps to <undefined>
    
    ----------------------------------------
```

Build Link: https://ci.appveyor.com/project/coala/coala-bears/build/1.0.9766/job/7keffjocn064913f#L95

**Comment by jayvdb** [comment]
Where is the upstream bug raised about this problem in safety `setup.py` ?

**Comment by jayvdb** [comment]
Also note that upstream they use AppVeyor.  If they havent had a build recently, maybe it breaks upstream if another PR is sent

If it is not failing for them, then we have some difference in our AppVeyor and their AppVeyor.

**Comment by RaiVaibhav** [comment]
related issue https://github.com/pyupio/safety/issues/119

**Comment by jayvdb** [comment]
@RaiVaibhav , please investigate their AppVeyor CI.
We ideally want to be helping upstream have CI in place which prevent us seeing breakages first.

**Comment by RaiVaibhav** [comment]
There was not any problem but the new approach is what I didn't like as they remove the `cve` from [safety](https://github.com/pyupio/safety/blob/master/safety/safety.py#L12) instead they used the `id`, so bear will give a message which will contain a [vuln_id](https://github.com/pyupio/safety/blob/master/safety/safety.py#L143) instead of `cve` so if user wants to know about its `cve` key for further search then he/she will have to find the `cve key` with the help of `vuln_id`

**Comment by RaiVaibhav** [comment]
As `cve` key is much more important instead of `vuln_id` as anyone can directly do a google search to know about that `cve`

**Comment by RaiVaibhav** [comment]
I don't have any problem in upgrading. :)

**Comment by jayvdb** [comment]
Thx @RaiVaibhav .  Is https://github.com/coala/coala-bears/issues/1684 fixed ?

**Comment by RaiVaibhav** [comment]
I didn't know about that issue, https://github.com/coala/coala-bears/issues/1684  will be fixed when I upgrade the Bear, that error was because of change in `safety` code.

**Comment by RaiVaibhav** [comment]
Assign me both and also please tell me that its urgent?

**Comment by jayvdb** [comment]
Yes quite urgent. Holds up other patches.
