### ISSUE TITLE
ESLintBear: KeyError: 'ruleId'

### ISSUE THREAD

**Issue by bekicot** [coala/coala-bears#2533]
Comand to run
```
coala --files=git-task-list/.eslintrc.js --bears=ESLintBear -V
```

```sh
[WARNING][09:13:51] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any use of config files with `-I`.
[DEBUG][09:13:52] Platform Darwin -- Python 3.6.5, coalib 0.11.0
Executing section cli...
[DEBUG][09:13:52] Files that will be checked:
/Users/bekicot/Projects/gsoc/git-task-list/.eslintrc.js
[DEBUG][09:13:52] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][09:13:52] Running bear ESLintBear...
[DEBUG][09:13:52] Running 'eslint --no-ignore --no-color -f=json --stdin --stdin-filename=/Users/bekicot/Projects/gsoc/git-task-list/.eslintrc.js --config /var/folders/mb/rnk_lt553cx16bn9nc52n3fc0000gn/T/tmpt_4i17u1'
[WARNING][09:13:53] Bear ESLintBear failed to run on file /Users/bekicot/Projects/gsoc/git-task-list/.eslintrc.js. Take a look at debug messages (`-V`) for further information.
[DEBUG][09:13:53] The bear ESLintBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/Users/bekicot/Library/Python/3.6/lib/python/site-packages/coalib/bears/Bear.py", line 282, in execute
    return [] if result is None else list(result)
  File "/usr/local/lib/python3.6/site-packages/bears/js/ESLintBear.py", line 88, in process_output
    if result['ruleId'] is not None else self)
KeyError: 'ruleId'
```

.eslintrc.js
```javascript
/*global module*/
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  plugins: [
    'ember'
  ],
  extends: [
    'eslint:recommended',
    'plugin:ember/recommended'
  ],
  env: {
    browser: true
  },
  rules: {
  },
  overrides: [
    // node files
    {
      files: [
        'ember-cli-build.js',
        'testem.js',
        'blueprints/*/index.js',
        'config/**/*.js',
        'lib/*/index.js'
      ],
      parserOptions: {
        sourceType: 'script',
        ecmaVersion: 2015
      },
      env: {
        browser: false,
        node: true
      }
    }
  ]
};
```

**Comment by jayvdb** [comment]
Here is a travis log of it

https://travis-ci.org/jayvdb/gsoc-prep-tasks/jobs/391075675#L958

**Comment by jayvdb** [comment]
The cause is ESLint emits a message `File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override.` without any ruleId or line number.
