### ISSUE TITLE
Python 3.3 unsupported test broken by bandit

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2537]
see https://travis-ci.org/coala/coala-bears/builds/392527549

This only occurs on master builds by default.  To test, you will need to modify the .travis.yml job configuration.

```console
Searching for bandit~=1.2
Reading https://pypi.python.org/simple/bandit/
Best match: bandit 1.4.0
Downloading https://files.pythonhosted.org/packages/45/b2/f5a4adb1e7773e6d631481b784ad49e6ec56aa81e9fdafcabf0fe3e0241a/bandit-1.4.0.tar.gz#sha256=cb977045497f83ec3a02616973ab845c829cdab8144ce2e757fe031104a9abd4
Processing bandit-1.4.0.tar.gz
Writing /tmp/easy_install-mkt_aw/bandit-1.4.0/setup.cfg
Running bandit-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mkt_aw/bandit-1.4.0/egg-dist-tmp-lvynhj
ERROR:root:Error parsing
```
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pbr/util.py", line 382, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/setuptools/__init__.py", line 124, in __init__
    _Command.__init__(self,dist)
  File "/opt/python/3.3.6/lib/python3.3/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```
```console
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-mkt_aw/bandit-1.4.0/setup.cfg: TypeError: dist must be a Distribution instance
+retval=1
+set +x
setup.py error code 1 ok
The command ".ci/check_unsupported.sh" exited with 1.
cache.2
store build cache
0.00s
2.69schange detected (content changed, file is created, or file is deleted):
/home/travis/.cache/pip/http/a/e/8/4/f/ae84f2ad63110adc3cf4c5da32252adb61136dcb578b4103e20105b9
changes detected, packing new archive
uploading archive
Done. Your build exited with 1.
```

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/2488
