### ISSUE TITLE
CommitBear: IndexError: list index out of range

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2642]
If there is no body for a commit, the following occurs

```py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coalib/bears/Bear.py", line 282, in execute
    return [] if result is None else list(result)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bears/vcs/git/GitCommitBear.py", line 135, in run
    **self.get_issue_checks_metadata().filter_parameters(kwargs))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bears/vcs/git/GitCommitBear.py", line 303, in check_issue_reference
    body = body.splitlines()[-1]
IndexError: list index out of range
```

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/issues/2031
