### ISSUE TITLE
Install only some selected bears instead of all bears

### ISSUE THREAD

**Issue by ankita240796** [coala/coala-bears#2681]
Hi, 

Is there a way to install only some of the selected bears instead of all bears. `cib` is mentioned in documentation but it is broken. So, is there some other way of doing this?

Thanks!

**Comment by jayvdb** [comment]
`cib` has just been fixed by @anctartica , so it is probably possible to use it now.
Hopefully @anctartica can help with this query.

We also have other WIP approaches to install only some of the pip bear dependencies, but they are a month or so away from completion.

**Comment by ankita240796** [comment]
Hi @jayvdb @anctartica ,  I tried using cib but I get this error:

```
Traceback (most recent call last):
  File "/home/ankita/Desktop/odk/odkenv/bin/cib", line 7, in <module>
    from coala_package_manager.installation_tool import main
  File "/home/ankita/Desktop/odk/odkenv/lib/python3.5/site-packages/coala_package_manager/installation_tool.py", line 29, in <module>
    from coalib.misc.Shell import call_without_output
ImportError: cannot import name 'call_without_output'
```

**Comment by anctartica** [comment]
Sorry for the late response. @ankita240796 
The current version of cib is broken. So, you could head over to https://gitlab.com/coala/cib, clone the repository and install latest version from there which should be working.

**Comment by ankita240796** [comment]
Thanks @anctartica!
