### ISSUE TITLE
CPDBear deperately needs updating

### ISSUE THREAD

**Issue by why-does-ie-still-exist** [coala/coala-bears#2751]
**Pertinent files:**
[research.zip](https://github.com/coala/coala-bears/files/2545435/research.zip)

After messing around setting up a development environment for a absurdly long time, I was able to run CPDBear, and there are numerous problmes which I ran into:

- CPDBear imports sub-libraries that don't exist in `coalib` (they likely once did exist, but not anymore)

- CPDBear uses packages like `PWD` and `bash` instead of the python `os` package

- CPDBear's language filtering cannot infer the language from a file type

- CPDBear uses language filtering, even though it's a simple enough bear that it's functionality should be implemented without language-specific AST parsing(it should probably just warn of similar code greater than length n)

- After debugging for a couple hours, the XML parsing broke entirely even though my code (provided in the .zip above) just passed the contents of files specified by `--files` into the parser

- There is a language option which seems to be inaccessible through a command line switch, and rather you must type in the language directly into a CLI:
`Please enter a value for the setting "language" (One of the supported languages of this bear.) needed by CPDBear for section "cli":`

My recommendation is a complete overhaul or deletion of this file, and a investigation into if other example bears in general also use outdated or nonexistent imports.

**If you want to replicate my results:**

Get a cloned version from `master` of coala-bears as of 11/3/2018
Install necessary dependencies from pip(there seems to be a problem with colorama versioning as of 11/3/2018) , so this is a struggle in its own right.

Use `setup.py install develop`

Update `coala-bears/bears/general/CPDBear.py` with the `CPDBear.py` file provied in the zip above, and `cd` into the provided example directory, running `coala --files py.js --bears CPDBear -V`

**Comment by jayvdb** [comment]
py.js contains

```js
var a = 1;
a = 1;
console.log(a);
```

**Comment by why-does-ie-still-exist** [comment]
A example of me running the `coala --files py.js --bears CPDBear -V`:

```
(JOHN) [REDACTED]\ExampleProj> coala --files py.js --bears CPDBear -V
?[33m[WARNING]?[0m[15:35:41] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag or suppress any u
se of config files with `-I`.?[0m
Please enter a value for the setting "language" (One of the supported languages of this bear.) needed by CPDBear for section "cli": 
Javascript
?[32m[DEBUG]?[0m[15:35:48] Platform Windows -- Python 3.6.4, coalib 0.11.0?[0m
Executing section cli...
?[32m[DEBUG]?[0m[15:35:48] Files that will be checked:
[REDACTED]\exampleproj\py.js?[0m
?[32m[DEBUG]?[0m[15:35:49] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.?[0m
?[32m[DEBUG]?[0m[15:35:50] Running bear CPDBear...?[0m
?[31m[ERROR]?[0m[15:35:50] This bear does not support files with the extension 'Javascript'.?[0m
?[33m[WARNING]?[0m[15:35:50] Bear CPDBear failed to run. Take a look at debug messages (`-V`) for further information.?[0m
?[32m[DEBUG]?[0m[15:35:50] The bear CPDBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you mig
ht want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "C:\Users\Michael Owens\Documents\JOHN\lib\site-packages\coalib\bears\Bear.py", line 282, in execute
    return [] if result is None else list(result)
  File "c:\users\michael owens\documents\coala-bears\bears\general\CPDBear.py", line 82, in run
    files = '\n'.join(str(v[1])[1, -1] for v in self.file_dict.items())
  File "c:\users\michael owens\documents\coala-bears\bears\general\CPDBear.py", line 82, in <genexpr>
    files = '\n'.join(str(v[1])[1, -1] for v in self.file_dict.items())
TypeError: string indices must be integers?[0m
```
