### ISSUE TITLE
RubySecurityBear: Runs into a JSON decode error

### ISSUE THREAD

**Issue by GreenBayRules** [coala/coala-bears#2753]
When running the RubySecurityBear with the testfile, it runs into a JSON decode error.

`coala -b RubySecurityBear -f test.py -V`

    [WARNING][17:51:07] 'cli' is an internally reserved section name. It may have been generated into     your coafile while running coala with `--save`. The settings in that section will inherit implicitly to all sections as defaults just like CLI args do. Please change the name of that section in your coafile to avoid any unexpected behavior.
    [DEBUG][17:51:07] Platform Linux -- Python 3.6.1, coalib 0.12.0.dev99999999999999
    [DEBUG][17:51:07] Since the configuration settings have changed since the last run, the cache will be flushed and rebuilt.
    [DEBUG][17:51:07] The file cache was successfully flushed.
    Executing section cli...
    [DEBUG][17:51:07] Files that will be checked:
    /home/sheshank/test.py
    [DEBUG][17:51:08] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
    [DEBUG][17:51:08] Running bear RubySecurityBear...
    [DEBUG][17:51:08] Running 'brakeman -f json /home/sheshank'
    [ERROR][17:51:08] Bear RubySecurityBear failed to run. Take a look at debug messages (`-V`) for further information.
    [DEBUG][17:51:08] The bear RubySecurityBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

    Traceback information is provided below:

    Traceback (most recent call last):
      File "/home/sheshank/coala/coalib/bears/Bear.py", line 454, in execute
        return [] if result is None else list(result)
      File "/home/sheshank/coala-bears/bears/ruby/RubySecurityBear.py", line 38, in process_output
        outputs = json.loads(output)
      File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ayan-b** [comment]
_Another issue with RubySecurityBear_, it correctly identifies vulnerablities but while applying actions, it throws file not found error (`cannot be printed because it refers to a file that doesn't seem to exist`).

**Comment by sangamcse** [comment]
> `coala -b RubySecurityBear -f test.py -V`

`RubySecurityBear` should be run on `ruby on rails` applications only.
