### ISSUE TITLE
pycodestyle silently discarding warnings

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2760]
Whilst working on coverage issues, I found that if I require all pycodestyle lines match the regex, the following occurs.

```py
[ERROR][03:47:24] Bear PycodestyleBear failed to run on file /home/travis/build/coala/coala-bears/bears/vcs/git/GitCommitBear.py. Take a look at debug messages (`-V`) for further information.
[DEBUG][03:47:24] The bear PycodestyleBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.
Traceback information is provided below:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coalib/bears/Bear.py", line 454, in execute
    return [] if result is None else list(result)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/bears/python/PycodestyleBear.py", line 78, in process_output
    line, column, message, rule = result.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```
https://travis-ci.org/coala/coala-bears/jobs/452210806

When spitting out the lines causing this, I find

```
[WARNING][04:04:11] Unexpected output 45 -303 W605 invalid escape sequence '\d'
[WARNING][04:04:31] Unexpected output 250 -55 W605 invalid escape sequence '\*'
259 -52 W605 invalid escape sequence '\|'
..
```
https://travis-ci.org/coala/coala-bears/jobs/452214629

All are in docstrings.  The first is in bears/vcs/git/GitCommitBear.py for the `\d`

> by GitHub in a refs/pull/(\d+)/merge git remote reference.

The second and third are bears/c_languages/codeclone_detection/ClangCountingConditions.py

> statement, i.e. within the operators \*, /, % and their associated compound

> operation, i.e. within the operators \|, & and their associated compound

There are two problems here, and they need to be fixed at the same time to avoid breaking the build.

1. pycodestyle isnt capturing all warnings, and was silently discarding them.

2. those errors are roughly correct and need to be fixed.

The `\d` is easy fixed.

The other two are much more problematic, as removing the `\` causes sphinx-build to then emit a warning:

```console
Warning, treated as error:
/home/travis/build/coala/coala-bears/bears/c_languages/codeclone_detection/ClangCountingConditions.py:docstring of bears.c_languages.codeclone_detection.ClangCountingConditions.in_binary_operation:1:Inline substitution_reference start-string without end-string.
```

**Comment by jayvdb** [comment]
The first problem was solved upstream, breaking this repo as the second wasnt solved at the same time.

The second problem was raised as dup https://github.com/coala/coala-bears/issues/2847
