### ISSUE TITLE
Errors while running SpaceConsistencyBear on.py

### ISSUE THREAD

**Issue by SimonZYC** [coala/coala-bears#2902]
I ran `coala --files=./\*.py --bears=SpaceConsistencyBear --save --json`. I used tabs in the python files. Errors:
```
[ERROR][13:14:40] During execution, we found that some required settings were not provided. They are:
use_spaces (from SpaceConsistencyBear) - True if spaces are to be used instead of tabs.
[ERROR][13:14:40] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][13:14:40] Exception was:
Traceback (most recent call last):

  File "/Users/user/Documents/code/coala_project/venv-coala/lib/python3.7/site-packages/coalib/coala_main.py", line 81, in run_coala
    arg_list=arg_list)

  File "/Users/user/Documents/code/coala_project/venv-coala/lib/python3.7/site-packages/coalib/settings/ConfigurationGathering.py", line 387, in gather_configuration
    log_printer)

  File "/Users/user/Documents/code/coala_project/venv-coala/lib/python3.7/site-packages/coalib/settings/SectionFilling.py", line 42, in fill_settings
    fill_section(section, acquire_settings, log_printer, all_bears)

  File "/Users/user/Documents/code/coala_project/venv-coala/lib/python3.7/site-packages/coalib/settings/SectionFilling.py", line 88, in fill_section
    new_vals = acquire_settings(log_printer, needed_settings, section)

  File "/Users/user/Documents/code/coala_project/venv-coala/lib/python3.7/site-packages/coalib/output/Interactions.py", line 26, in fail_acquire_settings
    raise AssertionError

AssertionError
{
  "results": {}
}
```
So if we do not use spaces in source files, does that mean we can not run
SpaceConsistencyBear?

**Comment by RuidongLiu** [comment]
I'm a newcomer here, can I be assigned this issue, plz.

**Comment by li-boxuan** [comment]
As the first line explains,

> [ERROR][13:14:40] During execution, we found that some required settings were not provided. They are:
use_spaces (from SpaceConsistencyBear) - True if spaces are to be used instead of tabs.

You need to provide that setting
