### ISSUE TITLE
AttributeError: 'CheckstyleBear' object has no attribute 'checkstyle_jar_file'

### ISSUE THREAD

**Issue by frextrite** [coala/coala-bears#2932]
```

[DEBUG][16:47:14] Running bear CheckstyleBear...
[DEBUG][16:47:14] The bear CheckstyleBear raised an exception. If you are the author of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the author of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "c:\users\amolg\documents\github\coala\coalib\bears\Bear.py", line 453, in execute
    result = self.run_bear_from_section(args, kwargs)
  File "c:\users\amolg\documents\github\coala\coalib\bears\Bear.py", line 436, in run_bear_from_section
    return self.run(*args, **kwargs)
  File "c:\users\amolg\documents\github\coala\coalib\bearlib\abstractions\Linter.py", line 663, in run
    **create_arguments_kwargs)
  File "c:\users\amolg\documents\github\coala-bears\bears\java\CheckstyleBear.py", line 102, in create_arguments
    return ('-jar', self.checkstyle_jar_file, '-c',
AttributeError: 'CheckstyleBear' object has no attribute 'checkstyle_jar_file'

```

OS: Windows 10 build 18362.207

**Comment by espatatis** [comment]
@frextrite can you give a little more details about the issue ?
