### ISSUE TITLE
WriteGoodLintBear: Crash due do setting

### ISSUE THREAD

**Issue by sims1253** [coala/coala-bears#802]
Setting was taken from doc page: https://github.com/coala-analyzer/bear-docs/blob/master/docs/WriteGoodLintBear.rst
Removing the check_* settings makes the bear run through

```
[m0hawk@m0hawkPC thesis]$ coala writegood -L DEBUG --flush-cache
[DEBUG][09:45:43] Platform Linux -- Python 3.5.2, pip 8.1.2, coalib 0.9.0.dev20160905160514
[DEBUG][09:45:43] The file cache was successfully flushed.
Executing section writegood...
[DEBUG][09:45:43] coala is run only on changed files, bears' log messages from previous runs may not appear. You may use the `--flush-cache` flag to see them.
[DEBUG][09:45:43] Files that will be checked:
/home/m0hawk/Documents/bachelorthesis/bachelor_thesis/thesis/linespots.md
The setting `check_ambiguos_words` is deprecated. Please use `allow_ambiguous_words` instead.
[DEBUG][09:45:43] Running bear WriteGoodLintBear...
[WARNING][09:45:43] Bear WriteGoodLintBear failed to run. Take a look at debug messages (`-L DEBUG`) for further information.
[DEBUG][09:45:43] The bear WriteGoodLintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/coalib/bears/Bear.py", line 249, in execute
    result = self.run_bear_from_section(args, kwargs)
  File "/usr/lib/python3.5/site-packages/coalib/bears/Bear.py", line 242, in run_bear_from_section
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/coalib/bearlib/abstractions/Linter.py", line 506, in run
    **create_arguments_kwargs)
  File "/usr/lib/python3.5/site-packages/coalib/bearlib/__init__.py", line 67, in wrapping_function
    return func(*args, **kwargs)
TypeError: create_arguments() got an unexpected keyword argument 'check_adverbs'
```

.coafile looks like this:
```
[writegood]
bears = WriteGoodLintBear
files = linespots.md
allow_adverbs = True
allow_ambiguous_word = True
allow_cliche_phrases = True
allow_extra_words = True
allow_passive_voice = True
allow_repeated_words = True
allow_so_beginning = True
allow_there_is = True
check_adverbs = True
check_ambiguos_words = True
check_cliche_exists = True
check_extra_words = True
check_passive_voice = True
check_repeated_words = True
check_so_beginning = True
check_there_is = True
```

**Comment by Asnelchristian** [comment]
there is a problem with you .coafile @sims1253, all the setting starting with `check_` were deprecated, and their default value were changed too, besides having `check_adverbs=True` and `allow_adverbs=True`, is contradicting  because it means you want `allow_adverbs` to be `True` and `False` at the same time

**Comment by Asnelchristian** [comment]
the bear-docs was misleading, but there is definitely a problem with the bear :(

**Comment by sims1253** [comment]
coming from the documentation, default for everything was true so then the default settings are bad.
just deleting all the check_* settings made it work for me too

**Comment by Asnelchristian** [comment]
all the settings with check_* were deprecated so, they shouldn't appear on the bear-docs or if they do they should be mention in the docs of the setting  that replace them

**Comment by Asnelchristian** [comment]
this is what needs to be addressed to solve this: https://github.com/coala/bear-docs/issues/11

**Comment by sils** [comment]
But this would be a bug in the deprecation then, is this still failing with an exception @sims1253 ?
