### ISSUE TITLE
chktex 1.7.3-5 fail LatexLintBearTest.test_invalid_files with UnicodeDecodeError

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#889]
chktex 1.7.2 (packaged into Ubuntu trusty) works correctly for the `bad_file` in `LatexLintBearTest`, however 1.7.3-1.7.5 all fail in `subprocess` while reading the result from `chktex`.

```
E           Running bear LatexLintBear...
E           Running 'chktex /tmp/tmpvifj3dsa'
E           Bear LatexLintBear failed to run. Take a look at debug messages (`-V`) for further information.
E           The bear LatexLintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.
E           
E           Traceback information is provided below:
E           
E           Traceback (most recent call last):
E             File "/.../coalib/bears/Bear.py", line 249, in execute
E               result = self.run_bear_from_section(args, kwargs)
E             File "/.../coalib/bears/Bear.py", line 242, in run_bear_from_section
E               return self.run(*args, **kwargs)
E             File "/.../coalib/bearlib/abstractions/Linter.py", line 521, in run
E               cwd=self.get_config_dir())
E             File "/.../coalib/misc/Shell.py", line 104, in run_shell_command
E               ret = p.communicate(stdin)
E             File "/usr/lib64/python3.5/subprocess.py", line 1068, in communicate
E               stdout, stderr = self._communicate(input, endtime, timeout)
E             File "/usr/lib64/python3.5/subprocess.py", line 1741, in _communicate
E               self.stdout.encoding)
E             File "/usr/lib64/python3.5/subprocess.py", line 979, in _translate_newlines
E               data = data.decode(encoding)
E           UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 116: invalid start byte
```

The problematic LateX is

```tex
{ .}
{ Sometext \\
```

With 1.7.2 the output is:
```
$ /usr/local/bin/chktex ~/tmp/bad.tex
ChkTeX v1.7.2 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with PCRE regex support.
Warning 26 in /home/jayvdb/tmp/bad.tex line 1: You ought to remove spaces in front of punctuation.
{ .}  
 ^
Warning 15 in /home/jayvdb/tmp/bad.tex line 2: No match found for `{'.
{ Sometext \\  
^
Warning 17 in /home/jayvdb/tmp/bad.tex line 2: Number of `{' doesn't match the number of `}'!


No errors printed; 3 warnings printed; No user suppressed warnings; No line suppressed warnings.
```
The output of 1.7.6 is identical except for the embedded version number.

The following is the output of 1.7.4, which is included in Ubuntu xenial and yakkety:

```
$ /usr/local/bin/chktex ~/tmp/bad.tex
ChkTeX v1.7.4 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with PCRE regex support.
Warning 26 in /home/jayvdb/tmp/bad.tex line 1: You ought to remove spaces in front of punctuation.
{ .}  
 ^
Warning 15 in  line 2: No match found for `{'.
�P�
^
Warning 17 in /home/jayvdb/tmp/bad.tex line 2: Number of `{' doesn't match the number of `}'!


No errors printed; 3 warnings printed; No user suppressed warnings; No line suppressed warnings.
See the manual for how to suppress some or all of these warnings/errors.
```

It appears this is the [upstream #49000](https://savannah.nongnu.org/bugs/?49000), which was fixed in 1.7.6 .

**Comment by jayvdb** [comment]
I'm not sure how big this bug is.  It looks quite bad ; maybe these releases should be blacklisted.
Or maybe it is possible to turn off displaying the source on all recent versions, which may help.

**Comment by jayvdb** [comment]
Dup of #317
